import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Cabecalho from "../../components/cabecalho/header";
import Rodape from "../../components/rodape/footer";
import style from '../../components/rodape/footer.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

<body className={inter.className}>

  <div className="elementos">
    <header>
      <Cabecalho/>
    </header>

    <div className={style.container}>{children}</div>

    <footer>
      <Rodape/>
    </footer>

  </div>

</body>
      
    </html>
  );
}
