// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PublicacoesDocumentDataSlicesSlice = PagPublicacoesSlice;

/**
 * Content for publicacoes documents
 */
interface PublicacoesDocumentData {
  /**
   * content field in *publicacoes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publicacoes.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * robo field in *publicacoes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: publicacoes.robo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  robo: prismic.ImageField<never>;

  /**
   * content2 field in *publicacoes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publicacoes.content2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content2: prismic.RichTextField;

  /**
   * robo2 field in *publicacoes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: publicacoes.robo2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  robo2: prismic.ImageField<never>;

  /**
   * Slice Zone field in *publicacoes*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: publicacoes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PublicacoesDocumentDataSlicesSlice> /**
   * Meta Description field in *publicacoes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: publicacoes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *publicacoes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: publicacoes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *publicacoes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: publicacoes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * publicacoes document from Prismic
 *
 * - **API ID**: `publicacoes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicacoesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PublicacoesDocumentData>,
    "publicacoes",
    Lang
  >;

export type AllDocumentTypes = PublicacoesDocument;

/**
 * Default variation for PagPublicacoes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PagPublicacoesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *PagPublicacoes*
 */
type PagPublicacoesSliceVariation = PagPublicacoesSliceDefault;

/**
 * PagPublicacoes Shared Slice
 *
 * - **API ID**: `pag_publicacoes`
 * - **Description**: PagPublicacoes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PagPublicacoesSlice = prismic.SharedSlice<
  "pag_publicacoes",
  PagPublicacoesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PublicacoesDocument,
      PublicacoesDocumentData,
      PublicacoesDocumentDataSlicesSlice,
      AllDocumentTypes,
      PagPublicacoesSlice,
      PagPublicacoesSliceVariation,
      PagPublicacoesSliceDefault,
    };
  }
}
